// The 8 tracks of Jéroboam's "Favorite" album. Audio files are gitignored
// (commercial masters — see CLAUDE.md "Real audio"); beatmaps are committed
// derived data generated by scripts/generate-beatmap.mjs.
//
// `bpm` is display/gait-animation only (aubio tempo estimates, see the
// table in CLAUDE.md) — actual beat timing comes from each track's beatmap.

export interface Track {
  id: string;
  title: string;
  bpm: number;
  audioUrl: string;
  beatmapUrl: string;
}

function track(num: string, id: string, title: string, bpm: number): Track {
  return {
    id,
    title,
    bpm,
    audioUrl: `/audio/${num}-${id}.mp3`,
    beatmapUrl: `/beatmaps/${id}.json`,
  };
}

export const TRACKS: Track[] = [
  track("01", "sweet-addiction", "Sweet Addiction", 113),
  track("02", "feeling-something", "Feeling Something", 101),
  track("03", "say-yeah", "Say Yeah", 123),
  // aubio hears sleepless-night an octave up (~175 BPM beat grid, "tempo"
  // says 159) — the real felt tempo is probably ~87. Playable but dense;
  // see BACKLOG.md before trusting this one.
  track("04", "sleepless-night", "Sleepless Night", 159),
  track("05", "unstoppable", "Unstoppable", 127),
  track("06", "surrender", "Surrender", 107),
  track("07", "light-up", "Light Up", 128),
  track("08", "the-game", "The Game", 96),
];

export const DEFAULT_TRACK_ID = "sweet-addiction";
